services:
  lvl:
    build:
      context: ./lvl
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/lib/database/database.sqlite
    # limit to 1 core and 1gb of ram
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 2
    volumes:
      - ./lvl_data:/var/lib/database

  elx:
    build:
      context: ./elx
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_PATH: /var/lib/database/elx.db
      POOL_SIZE: 1
      SECRET_KEY_BASE: "FOnb5ZpPjUIN9O+TIscqzV3e/usCzPLpTz/9b3EIt74mNehW8V6JBlED+lSnbWQ7"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 2
    volumes:
      - ./elx_data:/var/lib/database
