services:
  lvl:
    build:
      context: ./lvl
      dockerfile: franken.Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/lib/database/database.sqlite
    # limit to 1 core and 1gb of ram
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 2
    volumes:
      - ./lvl_data:/var/lib/database

  elx:
    build:
      context: ./elx
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - elx_migrator
    environment:
      DATABASE_PATH: /var/lib/database/elx.db
      SECRET_KEY_BASE: "FOnb5ZpPjUIN9O+TIscqzV3e/usCzPLpTz/9b3EIt74mNehW8V6JBlED+lSnbWQ7"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 2
    volumes:
      - ./elx_data:/var/lib/database

  elx_migrator:
    build:
      context: ./elx
      dockerfile: Dockerfile
      target: migrator
    environment:
      DATABASE_PATH: /var/lib/database/elx.db
      SECRET_KEY_BASE: "FOnb5ZpPjUIN9O+TIscqzV3e/usCzPLpTz/9b3EIt74mNehW8V6JBlED+lSnbWQ7"
    volumes:
      - ./elx_data:/var/lib/database

  rls:
    build:
      context: ./rls
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    environment:
      DATABASE_PATH: database/rls.db
      SECRET_KEY_BASE: "FOnb5ZpPjUIN9O+TIscqzV3e/usCzPLpTz/9b3EIt74mNehW8V6JBlED+lSnbWQ7"
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
        reservations:
          cpus: 2
    volumes:
      - ./rls_data:/rails/database
